services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    links:
      - mongodb
    volumes:
      - .:/usr/src/app
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
