GET http://localhost:3000/users

###

POST http://localhost:3000/users/register
Content-Type: application/json

{
    "name": "silas",
    "password": "test"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "name": "matteo",
    "password": "test"
}

###

POST http://localhost:3000/users/logout

###

GET http://localhost:3000/users/status

###

POST http://localhost:3000/users/change-username
Content-Type: application/json

{
    "newName": "test"
}

###

POST http://localhost:3000/users/change-password
Content-Type: application/json

{
    "password": "test1",
    "newPassword": "test"
}

###

GET http://localhost:3000/chats/

###

POST http://localhost:3000/chats/loadChats
Content-Type: application/json

###

POST http://localhost:3000/chats/loadChat
Content-Type: application/json

{
    "partner": "silas"
}

###

POST http://localhost:3000/chats/postMessage
Content-Type: application/json

{
    "partner": "matteo",
    "content": "Inception2"
}

###

POST http://localhost:3000/chats/removeMessage
Content-Type: application/json

{
    "partner": "tilman",
    "timestamp": 1707444451094
}